### ISSUE TITLE
Add datos.gob.mx webcomponents for navbar and footer

### ISSUE THREAD

**Issue by defvol** [mxabierto/procurement-analytics#4]
At datos.gob.mx we use several polymer components to avoid duplicating navigation and footer implementations:
https://github.com/mxabierto/componentes

We should use those to make this project compatible with datos.gob.mx

Usage:
https://github.com/mxabierto/dgm/blob/redesign/bower.json#L6
https://github.com/mxabierto/dgm/blob/redesign/_layouts/default.html#L6

Beware that a new style is in the works: https://github.com/mxabierto/procurement-analytics/issues/6

**Comment by defvol** [comment]
Loading dependencies

https://github.com/mxabierto/dgm/blob/redesign/_includes/head.html#L9
https://github.com/mxabierto/dgm/blob/redesign/_includes/head.html#L11

**Comment by markbrough** [comment]
@rodowi let me know if you need a hand with this - maybe you can point me to the new design, or I can use the existing components.

**Comment by defvol** [comment]
thanks @markbrough! it'd be great to get help on this

Please go ahead and try these components (ready and up-to-date)
https://github.com/mxabierto/dgm-navbar
https://github.com/mxabierto/dgm-footer
