### ISSUE TITLE
New stylesheet for datos.gob.mx

### ISSUE THREAD

**Issue by defvol** [mxabierto/procurement-analytics#6]
Should look like our next datos.gob.mx version (to be released next week)

Staging: http://dgm.bitslice.net

**Comment by defvol** [comment]
will need help from the design team -> @mxabierto/la-agencia 

@diegobeauroyre ¿cómo integramos el diseño?

**Comment by diegobeauroyre** [comment]
Colores quedarían así:

$base-color: #000000;             // Negro Oposición
$primary-color: #00cc99;                // Verde Apertura
$secondary-color: #474747;                   // Gris Opacidad

Están en: https://github.com/mxabierto/procurement-analytics/blob/develop/app/assets/styles/_variables.scss
Intente hacer un commit con estos cambios pero no tengo permiso :(

Debería verse así:

<img width="1231" alt="screen shot 2015-10-25 at 3 14 56 pm" src="https://cloud.githubusercontent.com/assets/6226604/10717946/55ac1a3c-7b2c-11e5-8e9d-1193c10887bb.png">

La tipo es Open Sans: https://www.google.com/fonts/specimen/Open+Sans

@rodowi 

Tipografía: Open Sans: https://www.google.com/fonts/specimen/Open+Sans

About page: https://drive.google.com/file/d/0B6xuFjlJEb0NVi1rQU1SM3kwb1k/view

**Comment by rodowi** [comment]
New header:
https://drive.google.com/open?id=0B6xuFjlJEb0NYzI2QjhMaTV0M3M

New footer:
https://drive.google.com/open?id=0B6xuFjlJEb0NVi1rQU1SM3kwb1k

**Comment by diegobeauroyre** [comment]
@rodowi Acá está la barra como tiene que ir: 

https://drive.google.com/folderview?id=0B6xuFjlJEb0NX1VqQWZPMUJZMm8&usp=sharing

**Comment by defvol** [comment]
@diegobeauroyre lo mandé a #18
