### ISSUE TITLE
Filters not working under custom domain

### ISSUE THREAD

**Issue by defvol** [mxabierto/procurement-analytics#8]
<img width="692" alt="screen shot 2015-10-20 at 7 05 37 pm" src="https://cloud.githubusercontent.com/assets/705860/10624406/9c63ab52-775d-11e5-820b-f793201ad3ac.png">

**Comment by markbrough** [comment]
Weird -- it works OK for me in Chrome and Firefox under:
http://contrataciones.datos.gob.mx/

Which browser are you using?

**Comment by defvol** [comment]
couldn't reproduce this again
working good

closing...
